#!/bin/bash

if [ "$1" = "remove" ]; then
    rm -rf /opt/xware-desktop/frontend
    rm -rf /opt/xware-desktop/daemon
    rm -rf /opt/xware-desktop/shared
fi

if [ "$1" = "purge" ]; then
    rm -rf /opt/xware-desktop
fi

#DEBHELPER#
exit 0
