#!/bin/bash
set -e

if [ "$1" = "configure" ]; then
    setcap CAP_SYS_ADMIN=+ep /opt/xware-desktop/chmns

    echo "欢迎使用Xware Desktop。"
    echo "设置方法和注意事项见项目主页。"
    echo "项目主页 https://github.com/Xinkai/XwareDesktop/wiki"
    echo "Github https://github.com/Xinkai/XwareDesktop"
fi

#DEBHELPER#
exit 0