#!/bin/bash
set -e

if [ "$1" = "configure" ]; then
    touch     /opt/xware_desktop/{settings.ini,mounts,xwared.ini}
    touch     /opt/xware_desktop/xware/cfg/{cid_store.dat,dht.cfg,download.cfg,etm.cfg,kad.cfg}
    chmod 664 /opt/xware_desktop/{settings.ini,mounts,xwared.ini}
    chmod 664 /opt/xware_desktop/xware/cfg/{cid_store.dat,dht.cfg,download.cfg,etm.cfg,kad.cfg}
    python3   -O -m compileall -q /opt/xware_desktop/frontend
    chown -R xware:xware /opt/xware_desktop
    setcap "CAP_SETUID=+ep CAP_SETGID=+ep" /opt/xware_desktop/permissioncheck

    echo "欢迎使用Xware Desktop。"
    echo "设置方法和注意事项见项目主页。"
    echo "项目主页 https://github.com/Xinkai/XwareDesktop/wiki"
    echo "Github https://github.com/Xinkai/XwareDesktop"
fi

#DEBHELPER#
exit 0