#!/bin/bash

if [ "$1" = "install" ]; then
    getent group xware >/dev/null 2>&1
    RET=$?
    if [ $RET -eq 0 ]; then
        useradd --no-create-home --gid xware --shell /bin/false --system xware
    else
        useradd --no-create-home --user-group --shell /bin/false --system xware
    fi
    rm -rf /tmp/thunder
fi

#DEBHELPER#
exit 0